env:
  browser: true
  es6: true

extends:
  - 'plugin:react-app/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module

plugins:
  - react-app
  - '@typescript-eslint'

rules: {
  "@typescript-eslint/explicit-function-return-type": "off",
}
